=== vojoup/BI-XML/countries/schema.dtd
<!ELEMENT country (section)+>
<!ATTLIST country
  name CDATA #REQUIRED>

<!ELEMENT section (property)+>
<!ATTLIST section
  name CDATA #REQUIRED>

<!ELEMENT property (name,value?,subproperty*)>

<!ELEMENT subproperty (name,value?)>

<!ELEMENT name (#PCDATA)>

<!ELEMENT value (#PCDATA)>

=== vojoup/BI-XML/countries/bulgaria.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--<!DOCTYPE country SYSTEM "schema.dtd">-->
<country name="Bulgaria">
    <section name="Introduction">
        <property>
            <name>Background</name>
            <value>The Bulgars, a Central Asian Turkic tribe, merged with the local Slavic inhabitants in the late 7th
                century to form the first Bulgarian state. In succeeding centuries, Bulgaria struggled with the
                Byzantine Empire to assert its place in the Balkans, but by the end of the 14th century the country was
                overrun by the Ottoman Turks. Northern Bulgaria attained autonomy in 1878 and all of Bulgaria became
                independent from the Ottoman Empire in 1908. Having fought on the losing side in both World Wars,
                Bulgaria fell within the Soviet sphere of influence and became a People's Republic in 1946. Communist
                domination ended in 1990, when Bulgaria held its first multiparty election since World War II and began
                the contentious process of moving toward political democracy and a market economy while combating
                inflation, unemployment, corruption, and crime. The country joined NATO in 2004 and the EU in 2007.
            </value>
        </property>
    </section>
    <section name="Geography">
        <property>
            <name>Location</name>
            <value>Southeastern Europe, bordering the Black Sea, between Romania and Turkey</value>
        </property>
        <property>
            <name>Geographic coordinates</name>
            <value>43 00 N, 25 00 E</value>
        </property>
        <property>
            <name>Map references</name>
            <value>Europe</value>
        </property>
        <property>
            <name>Area</name>
            <subproperty>
                <name>total</name>
                <value>110,879 sq km</value>
            </subproperty>
            <subproperty>
                <name>land</name>
                <value>108,489 sq km</value>
            </subproperty>
            <subproperty>
                <name>water</name>
                <value>2,390 sq km</value>
            </subproperty>
            <subproperty>
                <name>country comparison to the world</name>
                <value>106</value>
            </subproperty>
        </property>
        <property>
            <name>Area - comparative</name>
            <value>almost identical in size to Virginia; slightly larger than Tennessee</value>
        </property>
        <property>
            <name>Land boundaries</name>
            <subproperty>
                <name>total</name>
                <value>1,806 km</value>
            </subproperty>
            <subproperty>
                <name>border countries (5)</name>
                <value>Greece 472 km, Macedonia 162 km, Romania 605 km, Serbia 344 km, Turkey 223 km</value>
            </subproperty>
        </property>
        <property>
            <name>Coastline</name>
            <value>354 km</value>
        </property>
        <property>
            <name>Maritime claims</name>
            <subproperty>
                <name>territorial sea</name>
                <value>12 nm</value>
            </subproperty>
            <subproperty>
                <name>contiguous zone</name>
                <value>24 nm</value>
            </subproperty>
            <subproperty>
                <name>exclusive economic zone</name>
                <value>200 nm</value>
            </subproperty>
        </property>
        <property>
            <name>Climate</name>
            <value>temperate; cold, damp winters; hot, dry summers</value>
        </property>
        <property>
            <name>Terrain</name>
            <value>mostly mountains with lowlands in north and southeast</value>
        </property>
        <property>
            <name>Elevation</name>
            <value>highest point: Musala 2,925 m</value>
            <subproperty>
                <name>mean elevation</name>
                <value>472 m</value>
            </subproperty>
            <subproperty>
                <name>elevation extremes</name>
                <value>lowest point: Black Sea 0 m</value>
            </subproperty>
        </property>
        <property>
            <name>Natural resources</name>
            <value>bauxite, copper, lead, zinc, coal, timber, arable land</value>
        </property>
        <property>
            <name>Land use</name>
            <value>arable land 29.9%; permanent crops 1.5%; permanent pasture 15.5%</value>
            <subproperty>
                <name>agricultural land</name>
                <value>46.9%</value>
            </subproperty>
            <subproperty>
                <name>forest</name>
                <value>36.7%</value>
            </subproperty>
            <subproperty>
                <name>other</name>
                <value>16.4% (2011 est.)</value>
            </subproperty>
        </property>
        <property>
            <name>Irrigated land</name>
            <value>1,020 sq km (2012)</value>
        </property>
        <property>
            <name>Population - distribution</name>
            <value>a fairly even distribution throughout most of the country, with urban areas attracting larger
                populations
            </value>
        </property>
        <property>
            <name>Natural hazards</name>
            <value>earthquakes; landslides</value>
        </property>
        <property>
            <name>Environment - current issues</name>
            <value>air pollution from industrial emissions; rivers polluted from raw sewage, heavy metals, detergents;
                deforestation; forest damage from air pollution and resulting acid rain; soil contamination from heavy
                metals from metallurgical plants and industrial wastes
            </value>
        </property>
        <property>
            <name>Environment - international agreements</name>
            <subproperty>
                <name>party to</name>
                <value>Air Pollution, Air Pollution-Nitrogen Oxides, Air Pollution-Persistent Organic Pollutants, Air
                    Pollution-Sulfur 85, Air Pollution-Sulfur 94, Air Pollution-Volatile Organic Compounds,
                    Antarctic-Environmental Protocol, Antarctic-Marine Living Resources, Antarctic Treaty, Biodiversity,
                    Climate Change, Climate Change-Kyoto Protocol, Desertification, Endangered Species, Environmental
                    Modification, Hazardous Wastes, Law of the Sea, Marine Dumping, Ozone Layer Protection, Ship
                    Pollution, Wetlands
                </value>
            </subproperty>
            <subproperty>
                <name>but not ratified</name>
                <value>none of the selected agreements</value>
            </subproperty>
        </property>
        <property>
            <name>Geography - note</name>
            <value>strategic location near Turkish Straits; controls key land routes from Europe to Middle East and
                Asia
            </value>
        </property>
    </section>
    <section name="People and Society">
        <property>
            <name>Population</name>
            <value>7,101,510 (July 2017 est.)</value>
            <subproperty>
                <name>country comparison to the world</name>
                <value>103</value>
            </subproperty>
        </property>
        <property>
            <name>Nationality</name>
            <subproperty>
                <name>noun</name>
                <value>Bulgarian(s)</value>
            </subproperty>
            <subproperty>
                <name>adjective</name>
                <value>Bulgarian</value>
            </subproperty>
        </property>
        <property>
            <name>Ethnic groups</name>
            <value>Bulgarian 76.9%, Turkish 8%, Romani 4.4%, other 0.7% (including Russian, Armenian, and Vlach), other
                (unknown) 10% (2011 est.)
            </value>
            <subproperty>
                <name>note</name>
                <value>Romani populations are usually underestimated in official statistics and may represent 9â€“11% of
                    Bulgaria's population
                </value>
            </subproperty>
        </property>
        <property>
            <name>Languages</name>
            <value>Bulgarian (official) 76.8%, Turkish 8.2%, Romani 3.8%, other 0.7%, unspecified 10.5% (2011 est.)
            </value>
        </property>
        <property>
            <name>Religions</name>
            <value>Eastern Orthodox 59.4%, Muslim 7.8%, other (including Catholic, Protestant, Armenian Apostolic
                Orthodox, and Jewish) 1.7%, none 3.7%, unspecified 27.4% (2011 est.)
            </value>
        </property>
        <property>
            <name>Age structure</name>
            <subproperty>
                <name>0-14 years</name>
                <value>14.58% (male 532,924/female 502,277)</value>
            </subproperty>
            <subproperty>
                <name>15-24 years</name>
                <value>9.58% (male 354,872/female 325,538)</value>
            </subproperty>
            <subproperty>
                <name>25-54 years</name>
                <value>43.21% (male 1,576,980/female 1,491,489)</value>
            </subproperty>
            <subproperty>
                <name>55-64 years</name>
                <value>13.35% (male 445,412/female 502,924)</value>
            </subproperty>
            <subproperty>
                <name>65 years and over</name>
                <value>19.28% (male 554,486/female 814,608) (2017 est.)</value>
            </subproperty>
            <subproperty>
                <name>population pyramid</name>
            </subproperty>
        </property>
        <property>
            <name>Dependency ratios</name>
